steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'ci']

- id: 'setup function'
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'setup']
  env:
  - 'PROJECT=$PROJECT_ID'
  - 'FUNCTION=subscribeSlack'
  - 'GC_SLACK_STATUS=FAILURE TIMEOUT INTERNAL_ERROR'
  secretEnv: [SLACK_WEBHOOK_URL]

- id: 'deploy function'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
  'deploy',
  'subscribeSlack',
  '--trigger-topic=cloud-builds',
  '--entry-point=subscribe',
  '--region=europe-west1',
  '--runtime=nodejs8'
  ]

secrets:
- kmsKeyName: projects/atb-mobility-platform/locations/europe-west1/keyRings/amp/cryptoKeys/environment-secrets
  secretEnv:
    SLACK_WEBHOOK_URL: CiQAEoREfFYHGWLa3xh1P8UR5Br7pMSh2l0EHfz96q0wFnAnKU0SdgBKVmG/xMfq5bo9oOwpNNSmv52sjKLWm5vd7MHzm8RAh1e2s0+JT7BMpoEt/hgPnoYKpqbeebT9aFNGXPdxrAQ+WTnXb+OP+BVEIAjzbbZFyWeaAUsV03w6FoVa42mMGj4HP7Hei1YR3uNhB8ut3EsxCBK/tLQ=